### PR TITLE
Google

### PR DESCRIPTION
**Pull request by ben-jones**
Added code to encode urls as google search strings.

### CODE REVIEW

**Comment by gsathya** [comment]
Wait. This is based on your baidu changes right? Can you fix that pull request first?

**Comment by ben-jones** [comment]
I already addressed all of the comments from the Baidu branch but apparently it didn't push correctly (github was having issues earlier today.) I will push the update now.

**Comment by gsathya** [comment]
I merged your baidu branch. Can you rebase this branch on master and push? Thanks!

**Comment by ben-jones** [comment]
I rebased the branch. Please let me know what you think

**Comment by gsathya** [comment]
I think something went wrong. I see two of the same commits - https://github.com/ben-jones/htpt/compare/google

**Comment by ben-jones** [comment]
I see what you are talking about, but I have no idea how to fix this. Thoughts?

**Comment by gsathya** [comment]
I cherry picked the two commits. Thanks!

**Pull request closed without merging**
